# Fly.io deployment configuration for Nanshe API V2.
app = "nanshe-v2"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"
  PORT = "8080"
  DISABLE_SQLITE_FALLBACK = "1"

[http_service]
  internal_port = 8080
  force_https = true

  # garde les machines allumées (évite le scale-to-zero pour les WS)
  auto_start_machines = true
  auto_stop_machines = false
  # on veut 2 machines en permanence
  min_machines_running = 2

  processes = ["app"]

  # important pour WS: on raisonne en connexions, pas en "requests"
  [http_service.concurrency]
    type = "connections"
    soft_limit = 100
    hard_limit = 200

  [[http_service.checks]]
    name = "health"
    path = "/"
    method = "GET"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

# Taille PERSISTANTE des machines (appliquée à chaque deploy)
[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
